### ISSUE TITLE
mixing tabs with spaces in code

### ISSUE THREAD

**Issue by episodeyang** [sladebot/deepvo#2]
@sladebot I noticed that you are mixing tabs and spaces. Usually this can be made obvious by a good text-editor/IDE. Python shouldn't support tabs in the first case and your code is a classical example of what makes tab support hazardous.

I recommend PyCharm if you are not using it already. The pro-version has important deployment features and has a free student license.

Thanks for making your code available!

**Comment by andjsmile** [comment]
Can you tell me how to make this code work well? I can not run it. thanks

**Comment by 27Apoorva** [comment]
Hi @episodeyang ,
Can you tell me how is Inference function running for you?
Can you tell where all there is issue of tabbing and spaces?
Since inference is gonna run only on test data, it will never increase current_train_epoch. 
Also, for some reason when I run inference function, after every 5 poses, the ground truth has 0,0,0 pose. Can you tell what is wrong in the code?
Thanks a lot
